// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"errors"
	"github.com/PotatoEMR/PotatoEMR/utils"
	r4 "github.com/PotatoEMR/simple-fhir-client/r4"
	r4Client "github.com/PotatoEMR/simple-fhir-client/r4Client"
	"slices"

	"fmt"
	"net/http"
)

// https://build.fhir.org/observation-vitalsigns.html
func patient_ObservationVitalSigns(w http.ResponseWriter, req *http.Request) {
	patId := req.PathValue("patId")
	patEverything, err := client.PatientEverythingGrouped(patId)
	//map of observation time collected -> observation vital code -> observation
	//so we can create a spreadsheet ish thing
	//with a column of vitals collected at a given time
	//that has a row for each obs in vital signs panel
	vitalsByTimeAndCode := make(map[string]map[string]r4.Observation)
	for _, obs := range patEverything.Observations {
		obsTime, obsTimeErr := utils.ObservationTime(obs)
		if obsTimeErr == nil {
			for _, vitalSignsCode := range r4.VSObservation_vitalsignresult {
				for _, coding := range obs.Code.Coding {
					if coding.Code != nil && *coding.Code == *vitalSignsCode.Code {
						if vitalsByTimeAndCode[*obsTime] == nil {
							//might think this could go in higher loop, but we want the outer time map to only have times for vital sign observations
							//observation could be a normal observation with some other code, in which case doesn't make time -> code map
							vitalsByTimeAndCode[*obsTime] = make(map[string]r4.Observation)
						}
						vitalsByTimeAndCode[*obsTime][*vitalSignsCode.Code] = *obs
					}
				}
			}
		}
	}

	if err != nil {
		ErrorMsg(err).Render(req.Context(), w)
		return
	}
	if len(patEverything.Patients) != 1 {
		ErrorMsg(errors.New("Patient id "+patId+" not found on server "+client.BaseUrl)).Render(req.Context(), w)
		return
	}
	pat := patEverything.Patients[0]
	if pat.Id == nil || *pat.Id != patId {
		ErrorMsg(errors.New("Server returned patient without id "+patId)).Render(req.Context(), w)
		return
	}
	T_ObservationVitalSigns(pat, patEverything, vitalsByTimeAndCode).Render(req.Context(), w)
}

type VitalsTimeAndValues struct {
	Time   r4.FhirDateTime    `json:"time"`
	Values map[string]float64 `json:"values"`
}

func patient_ObservationVitalSignsCreate(w http.ResponseWriter, req *http.Request) {
	patId := req.PathValue("patId")
	var observations VitalsTimeAndValues
	if err := json.NewDecoder(req.Body).Decode(&observations); err != nil {
		ErrorMsg(errors.New("Could not parse submitted vital sign observations")).Render(req.Context(), w)
		fmt.Println(err)
		return
	}
	loincSystem := r4.VSObservation_vitalsignresult[0].System
	for _, codeAndName := range codeAndNames {
		obsFloat, ok := observations.Values[codeAndName.name]
		if ok {
			obsQty := r4.Quantity{Value: &obsFloat, Unit: &codeAndName.unit}
			obsCoding := r4.Coding{Code: &codeAndName.code, System: loincSystem}
			obsCodeableConcept := r4.CodeableConcept{Coding: []r4.Coding{obsCoding}}
			patRef := r4.Patient{Id: &patId}.ToRef()
			newObs := r4.Observation{Subject: &patRef, EffectiveDateTime: &observations.Time, ValueQuantity: &obsQty, Code: obsCodeableConcept}
			_, err := client.CreateObservation(&newObs)
			if err != nil {
				ErrorMsg(errors.New("ObservationVitalSignsCreate failed to create obs: "+err.Error())).Render(req.Context(), w)
				fmt.Println("err")
				return
			}
		}
	}
	patient_ObservationVitalSigns(w, req)
}

type codeAndName struct {
	code string
	name string
	unit string
}

var codeAndNames = []codeAndName{
	{code: "29463-7", name: "Body weight", unit: "kg"},
	{code: "8302-2", name: "Body height", unit: "cm"},
	{code: "9843-4", name: "Head circumference", unit: "cm"},
	{code: "39156-5", name: "Body mass index", unit: "kg/m²"},
	{code: "9279-1", name: "Respiratory Rate", unit: "/min"},
	{code: "8867-4", name: "Heart rate", unit: "/min"},
	{code: "2708-6", name: "Oxygen saturation", unit: "%O2"},
	{code: "8310-5", name: "Body temperature", unit: "°C"},
	{code: "85354-9", name: "Blood pressure systolic and diastolic", unit: "mm[Hg]"},
	{code: "8480-6", name: "Systolic blood pressure", unit: "mm[Hg]"},
	{code: "8462-4", name: "Diastolic blood pressure", unit: "mm[Hg]"},
}

func T_ObservationVitalSigns(pat *r4.Patient, patEverything *r4Client.ResourceGroup, vitalsByTimeAndCode map[string]map[string]r4.Observation) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h3>Vital Signs</h3><style>\n\t\ttable {\n\t\tborder-collapse: collapse;\n\t\t}\n\t\tth, td {\n\t\t\ttext-align: start;\n\t\tborder: 1px solid black;\n\t\tpadding: 5px;\n\t\t}\n\t\t</style> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}

			timeKeys := make([]string, 0)
			for k, _ := range vitalsByTimeAndCode {
				timeKeys = append(timeKeys, k)
			}
			slices.Sort(timeKeys)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<form id=\"vitalsForm\" hx-post=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(post_patient_observationVitalSigns, *pat.Id))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `Patient_ObservationVitalSigns.templ`, Line: 133, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-target=\"body\" hx-ext=\"form-json\" hx-push-url=\"false\" hx-indicator=\"#vitalsForm\" class=\"htmx-indicator\"><div style=\"width: fit-content;\"><table><tr><th>Time</th>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, k := range timeKeys {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<td>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(k)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `Patient_ObservationVitalSigns.templ`, Line: 145, Col: 14}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</td>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<td><input name=\"time\" required type=\"datetime-local\"></td></tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, codeAndName := range codeAndNames {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<tr><td>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(codeAndName.name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `Patient_ObservationVitalSigns.templ`, Line: 151, Col: 29}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</td>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, timeKey := range timeKeys {
					obs, ok := vitalsByTimeAndCode[timeKey][codeAndName.code]
					if ok {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<td>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						var templ_7745c5c3_Var6 string
						templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(utils.ObservationValueString(&obs))
						if templ_7745c5c3_Err != nil {
							return templ.Error{Err: templ_7745c5c3_Err, FileName: `Patient_ObservationVitalSigns.templ`, Line: 155, Col: 49}
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</td>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<td></td>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<td><input name=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs("values." + codeAndName.name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `Patient_ObservationVitalSigns.templ`, Line: 162, Col: 50}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" type=\"number\" step=\"0.01\" style=\"width: 80px; margin-right: 2px;\"><span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs("(" + codeAndName.unit + ")")
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `Patient_ObservationVitalSigns.templ`, Line: 165, Col: 44}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</span></td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</table><div style=\"text-align: right; margin-top: 2px;\"><button type=\"submit\">Save New Vitals Panel</button></div></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = patient_Base_Nav(pat, patEverything, get_patient_observationVitalSigns).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
