// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// all pages use base_nav for a few top links (not specific to a particular patient)
// and patient search
func Base_Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" style=\"height: 100%; margin: 0; padding: 0;\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"htmx-config\" content='{\"includeIndicatorStyles\": false}'><title>PotatoEMR</title><link rel=\"icon\" href=\"data:image/svg+xml,&lt;svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'&gt;&lt;text y='1em' font-size='80'&gt;🥔&lt;/text&gt;&lt;/svg&gt;\"><link rel=\"stylesheet\" href=\"/static/common.css\"><script defer src=\"/static/htmx.js\"></script><script defer src=\"/static/form-json.js\"></script><link rel=\"stylesheet\" href=\"/static/colors/default_light.css\"><script defer src=\"/static/potatoDrag.js\"></script></head><body style=\"display: flex; flex-direction: column;\"><nav hx-boost=\"true\" id=\"main-nav\" class=\"color-color1\" style=\"display: flex; padding-left: 2px; position: relative; border-bottom-width: 2px; border-bottom-style: solid; line-height: 1.2em;\"><a class=\"color-color1-hover\" style=\"padding: 4px\" href=\"/\">PotatoEMR🥔</a> <dialog id=\"search_patient_dialog\" hx-preserve class=\"color-color1 shadow\" style=\"position: absolute; top: 20vh; height: 50vh; right: 2vw; width: 70vw; padding: 4px; border-width: 2px; border-style: solid; border-radius: 8px; z-index: 99;\"><menu potato-drag style=\"cursor: move; display:flex; justify-content:space-between; align-items:center; margin: 0px; padding: 0px;\"><span>Patient Search</span> <button onclick=\"this.closest('dialog').close()\">✕</button></menu><hr potato-drag style=\"cursor: move;\" class=\"color-color1\"><section style=\"height: 300px; width: 60vw; overflow: auto; display:flex; flex-direction:column;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = T_SearchPatient().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section></dialog> <span class=\"color-color1-hover\" style=\"padding: 4px; cursor: pointer; text-decoration: underline;\" onclick=\"this.previousElementSibling.show()\">Search Patient</span> <a class=\"color-color1-hover\" style=\"padding: 4px\" href=\"/registerpatient\">Register Patient</a> <a class=\"color-color1-hover\" style=\"padding: 4px\" href=\"/calendar\">Calendar</a> <a class=\"color-color1-hover\" style=\"padding: 4px\" href=\"/patientlists\">Patient Lists</a> <a class=\"color-color1-hover\" style=\"padding: 4px\" href=\"/settings\">Settings</a></nav><main id=\"main-content\" class=\"color-color3\" style=\"flex: 1; overflow: auto;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
